#!/usr/bin/env python3
"""Cross-platform launcher for the local Locus review editor."""

from __future__ import annotations

import argparse
import os
import socket
import sys
import threading
import time
import webbrowser
from http.server import ThreadingHTTPServer
from pathlib import Path
from types import SimpleNamespace


def project_root() -> Path:
    return Path(__file__).resolve().parents[1]


def existing_path(candidates: list[Path], *, directory: bool) -> Path | None:
    for path in candidates:
        if directory and path.is_dir():
            return path
        if not directory and path.is_file():
            return path
    return None


def port_is_free(host: str, port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.settimeout(0.2)
        return sock.connect_ex((host, port)) != 0


def find_port(host: str, preferred: int) -> int:
    for port in range(preferred, preferred + 50):
        if port_is_free(host, port):
            return port
    raise RuntimeError(f"No free local port found from {preferred} to {preferred + 49}.")


def env_path(name: str) -> Path | None:
    value = os.environ.get(name, "").strip()
    return Path(value).expanduser() if value else None


def parse_args() -> argparse.Namespace:
    root = project_root()
    parser = argparse.ArgumentParser(description="Start the Locus local review editor.")
    parser.add_argument("--pic-dir", type=Path, default=None, help="Folder containing mol_*.png images.")
    parser.add_argument("--submission-csv", type=Path, default=None, help="Base submission.csv to review.")
    parser.add_argument("--risk-csv", type=Path, default=None, help="Top-risk CSV generated by Locus.")
    parser.add_argument("--output-dir", type=Path, default=root / "final_review_editor", help="Folder for autosaved review files.")
    parser.add_argument("--meta-path", type=Path, default=None, help="meta.md copied into exported zip.")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8766)
    parser.add_argument("--no-browser", action="store_true", help="Do not open the browser automatically.")
    return parser.parse_args()


def resolve_inputs(args: argparse.Namespace) -> SimpleNamespace:
    root = project_root()
    pic_candidates = [
        args.pic_dir,
        env_path("LOCUS_PIC_DIR"),
        root / "data" / "pic",
        root / "pic",
        Path("/tmp/bohrium_comp11252/data/pic"),
    ]
    submission_candidates = [
        args.submission_csv,
        env_path("LOCUS_SUBMISSION_CSV"),
        root / "Track1-V1-final-submit" / "submission.csv",
        root / "V1-final-submit" / "submission.csv",
    ]
    risk_candidates = [
        args.risk_csv,
        env_path("LOCUS_RISK_CSV"),
        root / "final_top300_review" / "top300_risk_list.csv",
    ]
    meta_candidates = [
        args.meta_path,
        env_path("LOCUS_META_MD"),
        root / "Track1-V1-final-submit" / "meta.md",
        root / "V1-final-submit" / "meta.md",
    ]

    pic_dir = existing_path([p for p in pic_candidates if p], directory=True)
    submission_csv = existing_path([p for p in submission_candidates if p], directory=False)
    risk_csv = existing_path([p for p in risk_candidates if p], directory=False)
    meta_path = existing_path([p for p in meta_candidates if p], directory=False)

    missing: list[str] = []
    if pic_dir is None:
        missing.append("image folder: put mol_*.png files in data/pic")
    if submission_csv is None:
        missing.append("submission CSV: expected Track1-V1-final-submit/submission.csv")
    if missing:
        print("Locus cannot start because required files are missing:\n", file=sys.stderr)
        for item in missing:
            print(f"- {item}", file=sys.stderr)
        if risk_csv is None:
            print("\nOptional risk CSV was not found; Locus can still run without it.", file=sys.stderr)
        print("\nSee USER_GUIDE_zh.md for the expected folder layout.", file=sys.stderr)
        raise SystemExit(2)

    return SimpleNamespace(
        pic_dir=pic_dir,
        submission_csv=submission_csv,
        risk_csv=risk_csv,
        output_dir=args.output_dir,
        meta_path=meta_path,
    )


def open_later(url: str) -> None:
    time.sleep(0.8)
    webbrowser.open(url)


def main() -> int:
    root = project_root()
    sys.path.insert(0, str(root))
    args = parse_args()
    inputs = resolve_inputs(args)
    port = find_port(args.host, args.port)

    from tools.review_edit_server import Handler, ReviewState

    state_args = SimpleNamespace(
        pic_dir=inputs.pic_dir,
        submission_csv=inputs.submission_csv,
        risk_csv=inputs.risk_csv,
        output_dir=inputs.output_dir,
        meta_path=inputs.meta_path,
    )
    state = ReviewState(state_args)
    Handler.state = state
    server = ThreadingHTTPServer((args.host, port), Handler)
    url = f"http://{args.host}:{port}/"

    print("\nLocus review editor is ready.")
    print(f"Open: {url}")
    print(f"Images: {inputs.pic_dir}")
    print(f"Working CSV: {state.working_csv}")
    print(f"Overrides: {state.overrides_csv}")
    print("Keep this window open while reviewing. Press Ctrl+C to stop.\n")

    if not args.no_browser:
        threading.Thread(target=open_later, args=(url,), daemon=True).start()

    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nLocus stopped.")
    finally:
        server.server_close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
